language: python

cache: pip

python:
- '3.4'
- '3.5'
- '3.6-dev'
- 'nightly'

matrix:
  allow_failures:
  - python: '3.6-dev'
  - python: 'nightly'

install:
- pip install -U pip setuptools
- pip install .
- pip install coverage flake8

script:
- coverage run --source=grablib setup.py test
- flake8 grablib/
- flake8 runtests.py
- grablib -V

after_success:
- ls -lha
- bash <(curl -s https://codecov.io/bash)
