language: python
sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - pip install coverage codecov flake8

script:
  - coverage run --source=grablib setup.py test
  - flake8 --max-line-length 120 grablib/

after_success:
  - codecov
