language: python

python:
  - "2.7"
  - "3.4"

install:
  - pip install coverage coveralls flake8

script:
  - coverage run --source=grablib setup.py test
  - flake8 --max-line-length 120 grablib/

after_success:
  - coveralls
