language: python

cache: pip

python:
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - pip install --upgrade pip
  - pip install .
  - pip install coverage codecov flake8 mock

script:
  - coverage run --source=grablib setup.py test
  - flake8 --max-line-length 120 grablib/
  - flake8 --max-line-length 120 runtests.py
  - grablib -V

after_success:
  - codecov
