language: python

cache: pip

python:
- '3.4'
- '3.5'
- '3.6-dev'
- 'nightly'

matrix:
  allow_failures:
  - python: 'nightly'

install:
- make install

script:
- make lint
- make test
- grablib -V

after_success:
- ls -lha
- bash <(curl -s https://codecov.io/bash)
